name: Hello GitHub Actions
on:
  push:
    branches:
      - dev

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem
        run: echo "GitHub Actions funcionando com sucesso!"